cliphist

diff --git a/bin/pass b/bin/pass
--- a/bin/pass
+++ b/bin/pass
@@ -1,7 +1,5 @@
 #!/usr/bin/env sh
 
-PATH="$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname "$0")" | paste -sd:)"
-
 die () {
     >&2 printf '%s: error: %s\n' "$(basename "$0")" "$@"
     exit 1
@@ -17,15 +15,30 @@ for a in "$@"; do
         -c|--clip) clip=1 ;;
     esac
 done
-if [ "$clip" -eq 1 ] && [ -x "$(command -v klipmenu)" ]; then
-    if [ "$(klipctl status)" = "enabled" ]; then
-        trap '{ sleep 1; klipctl enable; } &' EXIT HUP INT
+if [ "$clip" -eq 1 ]; then
+    if [ -x "$(command -v klipmenu)" ]; then
+        if [ "$(klipctl status)" = "enabled" ]; then
+            trap '{ sleep 1; klipctl enable; } &' EXIT HUP INT
+        fi
+        if ! klipctl disable 1>&2; then
+            case "$(klipctl status)" in
+                disabled|off) ;;
+                *) die 'was unable to disable klipmenu' ;;
+            esac
+        fi
     fi
-    if ! klipctl disable 1>&2; then
-        case "$(klipctl status)" in
-            disabled|off) ;;
-            *) die 'was unable to disable klipmenu' ;;
-        esac
+
+    cliphist="$(command -v cliphist)"
+    if [ -x "$cliphist" ]; then
+        if [ "$($cliphist -x-status)" = "enabled" ]; then
+            trap '{ sleep 1; $cliphist -x-enable; } &' EXIT HUP INT
+        fi
+        if ! $cliphist -x-disable 1>&2; then
+            case "$($cliphist -x-status)" in
+                disabled) ;;
+                *) die 'was unable to disable cliphist' ;;
+            esac
+        fi
     fi
 fi
 
@@ -33,4 +46,5 @@ if [ ! -x "$(command -v wl-copy)" ]; then
     unset WAYLAND_DISPLAY
 fi
 
+PATH="$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname "$0")" | paste -sd:)"
 pass "$@"
