Allow for lack of prevention for execution loop in case of shell wrappers

diff --git a/_patch/xdg_base_dir/wrappers/bash b/_patch/xdg_base_dir/wrappers/bash
--- a/_patch/xdg_base_dir/wrappers/bash
+++ b/_patch/xdg_base_dir/wrappers/bash
@@ -1,4 +1,8 @@
 #!/usr/bin/env sh
 
-. $XDG_LIB_DIR/shell/wrapper_exec.sh
-wrapper_exec --rcfile "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc" "$@"
+for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)"); do
+    if [ -x "$dir/$(basename $0)" ]; then
+        exec "$dir/$(basename $0)" --rcfile "${XDG_CONFIG_HOME:-$HOME/.config}/bash/bashrc" "$@"
+    fi
+done
+echo "$0: error: Wrapped command does not exist" >&2
diff --git a/_patch/xdg_base_dir/wrappers/csh b/_patch/xdg_base_dir/wrappers/csh
--- a/_patch/xdg_base_dir/wrappers/csh
+++ b/_patch/xdg_base_dir/wrappers/csh
@@ -4,5 +4,7 @@ PATH=$(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)" | paste -sd:)
 export REAL_HOME="$HOME"
 HOME="${XDG_CONFIG_HOME:-$HOME/.config}/csh"
 
-. $XDG_LIB_DIR/shell/wrapper_exec.sh
-wrapper_exec "$@"
+for dir in $(echo "$PATH" | tr ":" "\n" | grep -Fxv "$(dirname $0)"); do
+    [ -x "$dir/$(basename $0)" ] && exec "$dir/$(basename $0)" "$@"
+done
+echo "$0: error: Wrapped command does not exist" >&2
